"""add_location_profile_church_member_worker_transfer_absence_notice

Revision ID: fead1055eafd
Revises: 111a86ab3979
Create Date: 2026-03-21 14:08:35.333298+00:00
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = 'fead1055eafd'
down_revision = '111a86ab3979'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    worker_columns = {column["name"] for column in inspector.get_columns("workers")}
    worker_indexes = {index["name"] for index in inspector.get_indexes("workers")}

    if "approval_status" not in worker_columns:
        op.add_column(
            "workers",
            sa.Column("approval_status", sa.String(), server_default="approved", nullable=False),
        )
        worker_columns.add("approval_status")
    if "approved_by" not in worker_columns:
        op.add_column("workers", sa.Column("approved_by", sa.UUID(), nullable=True))
    if "approved_at" not in worker_columns:
        op.add_column("workers", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True))
    if "rejection_reason" not in worker_columns:
        op.add_column("workers", sa.Column("rejection_reason", sa.String(), nullable=True))
    if "ix_workers_approval_status" not in worker_indexes:
        op.create_index(op.f('ix_workers_approval_status'), 'workers', ['approval_status'], unique=False)
    fk_names = {fk.get("name") for fk in inspector.get_foreign_keys("workers")}
    if None not in fk_names and "fk_workers_approved_by_users" not in fk_names:
        op.create_foreign_key("fk_workers_approved_by_users", "workers", "users", ["approved_by"], ["user_id"])

    op.create_table('worker_absence_notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modify', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['program_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_absence_notices_created_at'), 'worker_absence_notices', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_absence_notices_event_id'), 'worker_absence_notices', ['event_id'], unique=False)
    op.create_index(op.f('ix_worker_absence_notices_status'), 'worker_absence_notices', ['status'], unique=False)
    op.create_index(op.f('ix_worker_absence_notices_worker_id'), 'worker_absence_notices', ['worker_id'], unique=False)
    op.create_table('location_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('founder_name', sa.String(), nullable=True),
    sa.Column('full_address', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('special_projects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modify', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_profiles_created_at'), 'location_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_location_profiles_location_id'), 'location_profiles', ['location_id'], unique=True)
    op.create_table('worker_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.String(), nullable=False),
    sa.Column('to_location_id', sa.String(), nullable=False),
    sa.Column('transfer_reason', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('origin_approved_by', sa.UUID(), nullable=True),
    sa.Column('origin_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_note', sa.Text(), nullable=True),
    sa.Column('destination_approved_by', sa.UUID(), nullable=True),
    sa.Column('destination_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_note', sa.Text(), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('letter_generated', sa.Boolean(), nullable=False),
    sa.Column('letter_url', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modify', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['destination_approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_transfers_created_at'), 'worker_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_transfers_from_location_id'), 'worker_transfers', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_worker_transfers_is_deleted'), 'worker_transfers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_worker_transfers_operation'), 'worker_transfers', ['operation'], unique=False)
    op.create_index(op.f('ix_worker_transfers_reference_number'), 'worker_transfers', ['reference_number'], unique=True)
    op.create_index(op.f('ix_worker_transfers_status'), 'worker_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_worker_transfers_to_location_id'), 'worker_transfers', ['to_location_id'], unique=False)
    op.create_index(op.f('ix_worker_transfers_worker_id'), 'worker_transfers', ['worker_id'], unique=False)
    op.create_table('church_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('member_since', sa.Date(), nullable=True),
    sa.Column('fellowship_id', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_worker', sa.Boolean(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('entered_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modify', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fellowship_id'], ['fellowships.fellowship_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_church_members_client_id'), 'church_members', ['client_id'], unique=False)
    op.create_index(op.f('ix_church_members_created_at'), 'church_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_church_members_fellowship_id'), 'church_members', ['fellowship_id'], unique=False)
    op.create_index(op.f('ix_church_members_is_deleted'), 'church_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_church_members_location_id'), 'church_members', ['location_id'], unique=False)
    op.create_index(op.f('ix_church_members_operation'), 'church_members', ['operation'], unique=False)
    op.create_index(op.f('ix_church_members_path'), 'church_members', ['path'], unique=False)
    op.create_index(op.f('ix_church_members_phone'), 'church_members', ['phone'], unique=False)
    op.create_index(op.f('ix_church_members_status'), 'church_members', ['status'], unique=False)
    op.create_index(op.f('ix_church_members_worker_id'), 'church_members', ['worker_id'], unique=False)
    op.alter_column('workers', 'approval_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'approval_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'approved'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_church_members_worker_id'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_status'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_phone'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_path'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_operation'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_location_id'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_is_deleted'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_fellowship_id'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_created_at'), table_name='church_members')
    op.drop_index(op.f('ix_church_members_client_id'), table_name='church_members')
    op.drop_table('church_members')
    op.drop_index(op.f('ix_worker_transfers_worker_id'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_to_location_id'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_status'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_reference_number'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_operation'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_is_deleted'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_from_location_id'), table_name='worker_transfers')
    op.drop_index(op.f('ix_worker_transfers_created_at'), table_name='worker_transfers')
    op.drop_table('worker_transfers')
    op.drop_index(op.f('ix_location_profiles_location_id'), table_name='location_profiles')
    op.drop_index(op.f('ix_location_profiles_created_at'), table_name='location_profiles')
    op.drop_table('location_profiles')
    op.drop_index(op.f('ix_worker_absence_notices_worker_id'), table_name='worker_absence_notices')
    op.drop_index(op.f('ix_worker_absence_notices_status'), table_name='worker_absence_notices')
    op.drop_index(op.f('ix_worker_absence_notices_event_id'), table_name='worker_absence_notices')
    op.drop_index(op.f('ix_worker_absence_notices_created_at'), table_name='worker_absence_notices')
    op.drop_table('worker_absence_notices')
    # ### end Alembic commands ###
