"""Add WorkerRemovalRequest model

Revision ID: 111a86ab3979
Revises: b1a2c3d4e5f6
Create Date: 2026-03-14 13:39:02.527646+00:00
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = '111a86ab3979'
down_revision = 'b1a2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_removal_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_by', sa.UUID(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modify', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path', sa.String(), nullable=False), # Fallback to String for ltree in migrations if type is missing

    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['escalated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_removal_requests_created_at'), 'worker_removal_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_removal_requests_path'), 'worker_removal_requests', ['path'], unique=False)
    op.create_index(op.f('ix_worker_removal_requests_status'), 'worker_removal_requests', ['status'], unique=False)
    op.create_index(op.f('ix_worker_removal_requests_worker_id'), 'worker_removal_requests', ['worker_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_removal_requests_worker_id'), table_name='worker_removal_requests')
    op.drop_index(op.f('ix_worker_removal_requests_status'), table_name='worker_removal_requests')
    op.drop_index(op.f('ix_worker_removal_requests_path'), table_name='worker_removal_requests')
    op.drop_index(op.f('ix_worker_removal_requests_created_at'), table_name='worker_removal_requests')
    op.drop_table('worker_removal_requests')
    # ### end Alembic commands ###
